version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: frontend
    image: frontend:frontend-v1.0.0
    restart: always
    ports:
      - "4000:4000"
